### ISSUE TITLE
I wouldn't call this a port.

### ISSUE THREAD

**Issue by trusktr** [trevorlinton/webkit.js#43]
It's WebKit compiled to browser-based JS.

A port would be a rewrite in JS, then maintained source code would be JS.

**Comment by trusktr** [comment]
A port would not run on top of an existing browser. This is a browser that needs another browser to run.

A port would be a standalone browser not running in another browser, maintained in JS.

**Comment by SirCmpwn** [comment]
I do not think you know what "port" means.

**Comment by trusktr** [comment]
Maybe I don't. :laugh:. I always thought a port was manual rewrite to another language. I was comparing it to C: compiling to ASM isn't porting to ASM.

**Comment by SirCmpwn** [comment]
Porting is the process of compiling something for a new architecture. You're right that compiling C to assembly isn't necessarily "porting", but if some software was designed for x86 assembly then compiling it to ARM assembly and fixing any resulting bugs is known as "porting".

**Comment by trusktr** [comment]
I wouldn't even bother opening such an issue nowadays anyways, ive learnt not to get into insignificant details that only waste time! Sorry for bothering, and nice concept. :)
